version: "3"
services:
  app:
    build: .
    ports:
      - "3000:80"
    environment:
      - REACT_APP_OPENWEATHERMAP_API_KEY=${REACT_APP_OPENWEATHERMAP_API_KEY}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
